#to run this with "docker build -f Dockerfile.dev ."

FROM node:16-alpine

WORKDIR /app

COPY package.json .
RUN npm install


RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

#we can remove copy instructions below as we are using docker-compose to reference volumes
COPY . .

CMD [ "npm", "run", "start" ]
